<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Models\DepartementModel.cs" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Realm" Version="20.1.0" />

		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />


		<PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
		<PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.2" />
		<PackageReference Include="DynamicData" Version="9.4.31" />

		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.6" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.6" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.6" />
		<PackageReference Include="YB.ParseLiveQueryDotNet" Version="3.8.4" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		
	</ItemGroup>

</Project>
