<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Models\DepartementModel.cs" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Realm" Version="20.1.0" />

		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		
	</ItemGroup>

</Project>
